# Generated by Django 5.2.4 on 2025-07-16 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_dislikes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='angries',
            field=models.ManyToManyField(blank=True, related_name='angry_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='funnies',
            field=models.ManyToManyField(blank=True, related_name='funny_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='loves',
            field=models.ManyToManyField(blank=True, related_name='loved_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
