# Generated by Django 5.2.4 on 2025-07-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', '1. Like'), ('dislike', '2. Dislike'), ('love', '3. Love'), ('funny', '4. Funny'), ('sad', '5. Sad'), ('shock', '6. Shock')], max_length=10),
        ),
    ]
